import json
import pathlib
import html

import jinja2
import termcolor

from importlib.resources import files

TEMPLATES = pathlib.Path(files("check50.renderer").joinpath("templates"))


def to_html(slug, results, version):
    with open(TEMPLATES / "results.html") as f:
        content = f.read()

    template = jinja2.Template(
        content, autoescape=jinja2.select_autoescape(enabled_extensions=("html",))
    )

    html = template.render(
        slug=slug,
        results=results,
        version=version,
        fmt_special_chars=_fmt_special_chars,
        color="rgba(161, 161, 161, 0.5)"
    )

    return html

def _fmt_special_chars(txt, color):
    """Converts a plaintext string into a string of HTML elements that highlights special chars."""
    def highlight_char(char, color):
        """Highlights and escapes a char."""
        return f"<span style='background-color:{color}; cursor: help;' title='This is an invisible or trailing special character.'>{repr(char)[1:-1]}</span>"

    # We'd like to interpret whitespace (ws) as HTML in only these specific cases:
    ws_to_html = {
        "\n": "<br/>",
        " ": "&nbsp;",
    }
    fmtted_txt = []

    for i, char in enumerate(txt):
        is_last = i == len(txt) - 1

        if not char.isprintable() and char not in ws_to_html:
            # Most special invisible characters, excluding those in ws_to_html, are highlighted
            fmtted_txt.append(highlight_char(char, color))
        elif char in ws_to_html:
            # If there's a trailing whitespace character, we highlight it
            if is_last:
                # Spaces aren't normally highlightable, so we convert to nbsp.
                if char == ' ':
                    char = ws_to_html[char]

                fmtted_txt.append(highlight_char(char, color))
            else:
                # Certain special chars are interpreted in HTML, without escaping or highlighting
                fmtted_txt.append(ws_to_html[char])
        else:
            # Non-special characters are unchanged
            fmtted_txt.append(char)

    # Return the text as a string of plaintext + html elements
    return ''.join(fmtted_txt)


def to_json(slug, results, version):
    return json.dumps({"slug": slug, "results": results, "version": version}, indent=4)


def to_ansi(slug, results, version, _log=False):
    lines = [termcolor.colored(_("Results for {} generated by check50 v{}").format(slug, version), "white", attrs=["bold"])]
    for result in results:
        if result["passed"]:
            lines.append(termcolor.colored(f":) {result['description']}", "green"))
        elif result["passed"] is None:
            lines.append(termcolor.colored(f":| {result['description']}", "yellow"))
            lines.append(termcolor.colored(f"    {result['cause'].get('rationale') or _('check skipped')}", "yellow"))
            if result["cause"].get("error") is not None:
                lines.append(f"    {result['cause']['error']['type']}: {result['cause']['error']['value']}")
                lines += (f"    {line.rstrip()}" for line in result["cause"]["error"]["traceback"])
        else:
            lines.append(termcolor.colored(f":( {result['description']}", "red"))
            if result["cause"].get("rationale") is not None:
                lines.append(termcolor.colored(f"    {result['cause']['rationale']}", "red"))
            if result["cause"].get("help") is not None:
                lines.append(termcolor.colored(f"    {result['cause']['help']}", "red"))

        if _log:
            lines += (f"    {line}" for line in result["log"])
    return "\n".join(lines)



